In [1]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential, load_model
from tensorflow.keras.layers import Dense, Flatten
from tensorflow.keras.optimizers import Adam
import random
import os
import matplotlib.pyplot as plt

In [2]:
# Konfigūruojame TensorFlow naudoti GPU, jei yra galimybė
gpus = tf.config.experimental.list_physical_devices('GPU')
if gpus:
    try:
        tf.config.experimental.set_visible_devices(gpus[0], 'GPU')
        for gpu in gpus:
            tf.config.experimental.set_memory_growth(gpu, True)
        print(f"GPU is available: {gpus[0]}")
    except RuntimeError as e:
        print(e)
else:
    print("No GPU available.")

GPU is available: PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')


In [4]:
# Treniruojame modelį naudojant savarankišką žaidimą
self_play(agent, env, 500, metrics)

# Išsaugome apmokytą modelį
save_model(model, model_path)

Episode 1/500:

1/1 [==============================] - 0s 44ms/step
Game:
[[0. 1. 2.]
 [1. 1. 1.]
 [2. 0. 2.]]
Reward: 1

Episode 2/500:

1/1 [==============================] - 0s 52ms/step
Game:
[[0. 0. 1.]
 [2. 2. 2.]
 [0. 1. 1.]]
Reward: 1

Episode 3/500:

1/1 [==============================] - 0s 44ms/step
Game:
[[2. 2. 2.]
 [1. 0. 1.]
 [0. 0. 1.]]
Reward: 1

Episode 4/500:

1/1 [==============================] - 0s 31ms/step
Game:
[[2. 1. 1.]
 [1. 2. 2.]
 [1. 2. 1.]]
Reward: 1

Episode 5/500:

1/1 [==============================] - 0s 32ms/step
Game:
[[1. 1. 2.]
 [2. 1. 1.]
 [2. 2. 1.]]
Reward: 1

Episode 6/500:

1/1 [==============================] - 0s 28ms/step
Game:
[[2. 0. 1.]
 [2. 2. 1.]
 [0. 1. 1.]]
Reward: 1

Episode 7/500:

1/1 [==============================] - 0s 64ms/step
Game:
[[0. 1. 2.]
 [1. 2. 1.]
 [2. 2. 1.]]
Reward: 1

Episode 8/500:

1/1 [==============================] - 0s 62ms/step
Game:
[[1. 1. 1.]
 [2. 1. 2.]
 [0. 2. 0.]]
Reward: 1

Episode 9/500:

1/1 [===

In [5]:
# Parodome mokymo metrikų grafiką
metrics.plot()

# Vertiname apmokytą modelį prieš atsitiktinį agentą
evaluate(agent, env, 100)

1/1 [==============================] - 0s 45ms/step
Win Rate: 0.55, Loss Rate: 0.45, Draw Rate: 0.00
